release_env: dev
rc:
  base:
    port: 7003
    admport: 7002
  deskpro:
    url: https://peeringdb.deskpro.com/api/v2/20180226

misc:
  tutorial_mode: False
  suggestions:
    org_id: 0
  session:
    domain: peeringdb.com
    secure: True
  ixf:
    postmortem:
      limit: 250
  ratelimits:
    request_login_POST: "4/m"
    view_request_ownership_POST: "3/m"
    view_request_ownership_GET: "3/m"
    view_affiliate_to_org_POST: "3/m"
    resend_confirmation_mail: "2/m"
    view_verify_POST: "2/m"
    view_username_retrieve_initiate: "2/m"
    request_translation: "2/m"
    view_import_ixlan_ixf_preview: "1/m"
    view_import_net_ixf_postmortem: "1/m"
  api:
    throtteling:
      enabled: true
      anon: "100/second"
      user: "100/second"
    compat:
      client:
        min: "0,6"
        max: "255,0"
      backends:
        - name: django_peeringdb
          min: "0,6"
          max: "255,0"
  maintenance:
    lockfile: "maintenance.lock"

locale:
  # enable these locale
  - en
  - pt
  - it
  - cs_CZ
  - de_DE
  - el_GR
  - es_ES
  - fr_FR
  - ja_JP
  - ro_RO
  - ru_RU
  - zh_CN
  - zh_TW


data_quality:
  # maximum value to allow in network.info_prefixes4
  max_prefix_v4_limit: 500000
  # maximum value to allow in network.info_prefixes6
  max_prefix_v6_limit: 50000
  # minimum allowed length of a v4 prefix
  min_prefixlen_v4: 18
  # maximum allowed length of a v4 prefix
  max_prefixlen_v4: 28
  # minimum allowed length of a v6 prefix
  min_prefixlen_v6: 64
  # maximum allowed length of a v6 prefix
  max_prefixlen_v6: 116


install:
  groups:

  - type: tmpl
    dir: tmpl
    render_files: true
    skip: ^\.

  # peeringdb static files
  - type: copy
    dir: $SRC_DIR$/peeringdb_server/static
    pattern: ^$SRC_DIR$
    replace: peeringdb
    skip: ^\.

  - type: copy
    pattern: ^$SRC_DIR$
    replace: peeringdb
    files:
    - $SRC_DIR$/manage.py
    - $SRC_DIR$/peeringdb_server/api_cache.py
    - $SRC_DIR$/peeringdb_server/__init__.py
    - $SRC_DIR$/peeringdb_server/admin.py
    - $SRC_DIR$/peeringdb_server/models.py
    - $SRC_DIR$/peeringdb_server/views.py
    - $SRC_DIR$/peeringdb_server/data_views.py
    - $SRC_DIR$/peeringdb_server/org_admin_views.py
    - $SRC_DIR$/peeringdb_server/autocomplete_views.py
    - $SRC_DIR$/peeringdb_server/apps.py
    - $SRC_DIR$/peeringdb_server/signals.py
    - $SRC_DIR$/peeringdb_server/inet.py
    - $SRC_DIR$/peeringdb_server/mail.py
    - $SRC_DIR$/peeringdb_server/urls.py
    - $SRC_DIR$/peeringdb_server/search.py
    - $SRC_DIR$/peeringdb_server/stats.py
    - $SRC_DIR$/peeringdb_server/deskpro.py
    - $SRC_DIR$/peeringdb_server/serializers.py
    - $SRC_DIR$/peeringdb_server/admin_commandline_tools.py
    - $SRC_DIR$/peeringdb_server/rest.py
    - $SRC_DIR$/peeringdb_server/renderers.py
    - $SRC_DIR$/peeringdb_server/settings.py
    - $SRC_DIR$/peeringdb_server/forms.py
    - $SRC_DIR$/peeringdb_server/export_views.py
    - $SRC_DIR$/peeringdb_server/validators.py
    - $SRC_DIR$/peeringdb_server/db_router.py
    - $SRC_DIR$/peeringdb_server/mock.py
    - $SRC_DIR$/peeringdb_server/maintenance.py
    - $SRC_DIR$/peeringdb_server/import_views.py
    - $SRC_DIR$/peeringdb_server/ixf.py
    - $SRC_DIR$/peeringdb_server/management/__init__.py
    - $SRC_DIR$/peeringdb_server/management/commands/__init__.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_deskpro_publish.py
    - $SRC_DIR$/peeringdb_server/management/commands/_db_command.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_api_cache.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_api_test.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_fac_merge.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_fac_merge_undo.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_renumber_lans.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_undelete.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_reversion_inspect.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_status.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_whois.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_sponsorship_notify.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_batch_replace.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_ixp_merge.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_geosync.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_ixf_ixp_member_import.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_stats.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_deskpro_requeue.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_generate_test_data.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_wipe.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_maintenance.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_process_admin_tool_command.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_load_data.py
    - $SRC_DIR$/peeringdb_server/management/commands/pdb_fix_status_history.py
    - $SRC_DIR$/peeringdb_server/migrations/__init__.py
    - $SRC_DIR$/peeringdb_server/migrations/0001_initial.py
    - $SRC_DIR$/peeringdb_server/migrations/0002_partnernship_model.py
    - $SRC_DIR$/peeringdb_server/migrations/0003_add_lat_lon_to_address_models.py
    - $SRC_DIR$/peeringdb_server/migrations/0004_geocode_fields.py
    - $SRC_DIR$/peeringdb_server/migrations/0005_lat_lon_field_rename.py
    - $SRC_DIR$/peeringdb_server/migrations/0006_network_allow_ixp_update.py
    - $SRC_DIR$/peeringdb_server/migrations/0007_ixlan_json_member_list_url.py
    - $SRC_DIR$/peeringdb_server/migrations/0008_ixf_import_log.py
    - $SRC_DIR$/peeringdb_server/migrations/0009_rename_json_member_list_field.py
    - $SRC_DIR$/peeringdb_server/migrations/0010_rename_ixf_ixp_member_list_url.py
    - $SRC_DIR$/peeringdb_server/migrations/0011_commandline_tool.py
    - $SRC_DIR$/peeringdb_server/migrations/0012_deskpro.py
    - $SRC_DIR$/peeringdb_server/migrations/0013_user_locale.py
    - $SRC_DIR$/peeringdb_server/migrations/0014_clt_description.py
    - $SRC_DIR$/peeringdb_server/migrations/0015_email_address.py
    - $SRC_DIR$/peeringdb_server/migrations/0016_auto_20190110_2321.py
    - $SRC_DIR$/peeringdb_server/migrations/0017_ixf_ixp_import_enabled.py
    - $SRC_DIR$/peeringdb_server/migrations/0018_set_ixf_ixp_import_enabled.py
    - $SRC_DIR$/peeringdb_server/migrations/0019_auto_20190819_1133.py
    - $SRC_DIR$/fixtures/initial_data.json
    - $SRC_DIR$/peeringdb_server/templates/admin/admin_extended.html
    - $SRC_DIR$/peeringdb_server/templates/admin/user-organizations.html
    - $SRC_DIR$/peeringdb_server/templates/site/request-ownership.html
    - $SRC_DIR$/peeringdb_server/templates/admin/org_merge_tool.html
    - $SRC_DIR$/peeringdb_server/templates/admin/change_form.html
    - $SRC_DIR$/peeringdb_server/templates/admin/peeringdb_server/commandlinetool/change_list.html
    - $SRC_DIR$/peeringdb_server/templates/admin/peeringdb_server/commandlinetool/preview_command.html
    - $SRC_DIR$/peeringdb_server/templates/admin/peeringdb_server/commandlinetool/prepare_command.html
    - $SRC_DIR$/peeringdb_server/templates/admin/peeringdb_server/commandlinetool/run_command.html
    - $SRC_DIR$/peeringdb_server/templates/site/verify.html
    - $SRC_DIR$/peeringdb_server/templates/site/register.html
    - $SRC_DIR$/peeringdb_server/templates/site/oauth-login.html
    - $SRC_DIR$/peeringdb_server/templates/account/email_confirm.html
    - $SRC_DIR$/peeringdb_server/templates/account/login.html
    - $SRC_DIR$/peeringdb_server/templates/site/index.html
    - $SRC_DIR$/peeringdb_server/templates/site/header.html
    - $SRC_DIR$/peeringdb_server/templates/site/footer.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_header.html
    - $SRC_DIR$/peeringdb_server/templates/site/view.html
    - $SRC_DIR$/peeringdb_server/templates/site/error.html
    - $SRC_DIR$/peeringdb_server/templates/site/error_404.html
    - $SRC_DIR$/peeringdb_server/templates/site/error_403.html
    - $SRC_DIR$/peeringdb_server/templates/site/maintenance.html
    - $SRC_DIR$/peeringdb_server/templates/site/profile-change-password.html
    - $SRC_DIR$/peeringdb_server/templates/site/profile-change-email.html
    - $SRC_DIR$/peeringdb_server/templates/site/profile-affiliate.html
    - $SRC_DIR$/peeringdb_server/templates/site/profile-confirm-email.html
    - $SRC_DIR$/peeringdb_server/templates/site/profile-pick-language.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_network_side.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_network_bottom.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_exchange_side.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_exchange_bottom.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_facility_side.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_facility_bottom.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_network_assets.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_facility_assets.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_exchange_assets.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_organization_side.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_organization_bottom.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_organization_assets.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_exchange_tools.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_organization_tools.html
    - $SRC_DIR$/peeringdb_server/templates/site/entity_create.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_network_tools.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_facility_tools.html
    - $SRC_DIR$/peeringdb_server/templates/site/login.html
    - $SRC_DIR$/peeringdb_server/templates/site/inline_search.html
    - $SRC_DIR$/peeringdb_server/templates/site/inline_search_hidden.html
    - $SRC_DIR$/peeringdb_server/templates/site/verification_banner.html
    - $SRC_DIR$/peeringdb_server/templates/site/tutorial_mode_banner.html
    - $SRC_DIR$/peeringdb_server/templates/site/header-sponsorships.html
    - $SRC_DIR$/peeringdb_server/templates/site/search_result_frame.html
    - $SRC_DIR$/peeringdb_server/templates/site/search_result.html
    - $SRC_DIR$/peeringdb_server/templates/site/base.html
    - $SRC_DIR$/peeringdb_server/templates/site/advanced-search.html
    - $SRC_DIR$/peeringdb_server/templates/site/password-reset.html
    - $SRC_DIR$/peeringdb_server/templates/site/header-partnerships.html
    - $SRC_DIR$/peeringdb_server/templates/site/partnerships.html
    - $SRC_DIR$/peeringdb_server/templates/site/username-retrieve-complete.html
    - $SRC_DIR$/peeringdb_server/templates/site/username-retrieve.html
    - $SRC_DIR$/peeringdb_server/templates/site/entity_suggest.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_suggest_fac.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_suggest_ix.html
    - $SRC_DIR$/peeringdb_server/templates/site/view_suggest_net.html
    - $SRC_DIR$/peeringdb_server/templates/email/username-retrieve.txt
    - $SRC_DIR$/peeringdb_server/templates/email/password-reset.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-org-admin-user-affil.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-pdb-admin-user-affil.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-org-admin-user-affil-denied.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-org-admin-user-affil-approved.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-sponsorship-admin-expiration.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-pdb-admin-vq.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-pdb-admin-asnauto-skipvq.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-pdb-admin-asnauto-entity-creation.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-pdb-admin-asnauto-affil.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-org-admin-merge.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-user-uoar-ownership-approved.txt
    - $SRC_DIR$/peeringdb_server/templates/email/notify-pdb-admin-rdap-error.txt
    - $SRC_DIR$/peeringdb_server/templates/rest_framework_swagger/base.html
    - $SRC_DIR$/peeringdb_server/templatetags/__init__.py
    - $SRC_DIR$/peeringdb_server/templatetags/util.py
    - $SRC_DIR$/peeringdb_server/templates/site/advanced-search-net.html
    - $SRC_DIR$/peeringdb_server/templates/site/advanced-search-fac.html
    - $SRC_DIR$/peeringdb_server/templates/site/advanced-search-ix.html
    - $SRC_DIR$/peeringdb_server/templates/site/sponsorships.html
    - $SRC_DIR$/peeringdb_server/templates/site/simple_content.html
    - $SRC_DIR$/peeringdb_server/templates/site/aup.html
    - $SRC_DIR$/peeringdb_server/templates/site/about.html
    - $SRC_DIR$/peeringdb_server/templates/oauth2_provider/base.html
